import {
  CurrencyType,
  ISecurities,
  TransactionType,
} from '../../../../core/dto/shared/Isecurities';
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-securities',
  templateUrl: './securities.component.html',
  encapsulation: ViewEncapsulation.None,
  styleUrls: ['./securities.component.scss'],
})
export class SecuritiesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}

  public data: ISecurities[] = [
    {
      Days: 200,
      TradeDate: new Date().toDateString(),
      TranType: TransactionType.BUY,
      MngrCode: 'ABC',
      Ticker: 'string',
      Name: 'string',
      CUSIP: 'string',
      MaturityDate: new Date().toDateString(),
      Yield: 'string',
      CUR: CurrencyType.USD,
      Portfolio: 'string',
      Quantity: 10,
      Trader: 'string',
      Strategy: 'string',
      DUSCode: 'string',
      Reason: 'string',
      FlagComment: '',
      Note: '',
      IsApproved: false,
      IsFlagged: false,
    },

    {
      Days: 200,
      TradeDate: new Date().toDateString(),
      TranType: TransactionType.BUY,
      MngrCode: 'OIU',
      Ticker: 'string',
      Name: 'string',
      CUSIP: 'string',
      MaturityDate: new Date().toDateString(),
      Yield: 'string',
      CUR: CurrencyType.USD,
      Portfolio: 'string',
      Quantity: 10,
      Trader: 'string',
      Strategy: 'string',
      DUSCode: 'string',
      Reason: 'string',
      FlagComment: '',
      Note: '',
      IsApproved: false,
      IsFlagged: false,
    },
    {
      Days: 223,
      TradeDate: new Date().toDateString(),
      TranType: TransactionType.BUY,
      MngrCode: 'MNB',
      Ticker: 'string',
      Name: 'string',
      CUSIP: 'string',
      MaturityDate: new Date().toDateString(),
      Yield: 'string',
      CUR: CurrencyType.USD,
      Portfolio: 'string',
      Quantity: 10,
      Trader: 'string',
      Strategy: 'string',
      DUSCode: 'string',
      Reason: 'string',
      FlagComment: '',
      Note: '',
      IsApproved: false,
      IsFlagged: false,
    },
    {
      Days: 127,
      TradeDate: new Date().toDateString(),
      TranType: TransactionType.BUY,
      MngrCode: 'KJGK',
      Ticker: 'string',
      Name: 'string',
      CUSIP: 'string',
      MaturityDate: new Date().toDateString(),
      Yield: 'string',
      CUR: CurrencyType.USD,
      Portfolio: 'string',
      Quantity: 10,
      Trader: 'string',
      Strategy: 'string',
      DUSCode: 'string',
      Reason: 'string',
      FlagComment: '',
      Note: '',
      IsApproved: false,
      IsFlagged: false,
    },

    {
      Days: 348,
      TradeDate: new Date().toDateString(),
      TranType: TransactionType.BUY,
      MngrCode: 'MJHK',
      Ticker: 'string',
      Name: 'string',
      CUSIP: 'string',
      MaturityDate: new Date().toDateString(),
      Yield: 'string',
      CUR: CurrencyType.USD,
      Portfolio: 'string',
      Quantity: 10,
      Trader: 'string',
      Strategy: 'string',
      DUSCode: 'string',
      Reason: 'string',
      FlagComment: '',
      Note: '',
      IsApproved: false,
      IsFlagged: false,
    },

    {
      Days: 98,
      TradeDate: new Date().toDateString(),
      TranType: TransactionType.BUY,
      MngrCode: 'KJH',
      Ticker: 'string',
      Name: 'string',
      CUSIP: 'string',
      MaturityDate: new Date().toDateString(),
      Yield: 'string',
      CUR: CurrencyType.USD,
      Portfolio: 'string',
      Quantity: 10,
      Trader: 'string',
      Strategy: 'string',
      DUSCode: 'string',
      Reason: 'string',
      FlagComment: '',
      Note: '',
      IsApproved: false,
      IsFlagged: false,
    },

    {
      Days: 298,
      TradeDate: new Date().toDateString(),
      TranType: TransactionType.BUY,
      MngrCode: 'AKS',
      Ticker: 'string',
      Name: 'string',
      CUSIP: 'string',
      MaturityDate: new Date().toDateString(),
      Yield: 'string',
      CUR: CurrencyType.USD,
      Portfolio: 'string',
      Quantity: 10,
      Trader: 'string',
      Strategy: 'string',
      DUSCode: 'string',
      Reason: 'string',
      FlagComment: '',
      Note: '',
      IsApproved: false,
      IsFlagged: false,
    },

    {
      Days: 789,
      TradeDate: new Date().toDateString(),
      TranType: TransactionType.BUY,
      MngrCode: 'SDJH',
      Ticker: 'string',
      Name: 'string',
      CUSIP: 'string',
      MaturityDate: new Date().toDateString(),
      Yield: 'string',
      CUR: CurrencyType.INR,
      Portfolio: 'string',
      Quantity: 10,
      Trader: 'string',
      Strategy: 'string',
      DUSCode: 'string',
      Reason: 'string',
      FlagComment: '',
      Note: '',
      IsApproved: false,
      IsFlagged: false,
    },
  ];
}
